### ISSUE TITLE
Python main.py not starting 

### ISSUE THREAD

**Issue by Noofayroz** [fabston/TradingView-Webhook-Bot#112]
## Describe the bug
i did everything correct but i am not able to launch the bot using **Python main.py**  Command i left the terminal as it is and i tried to start it from another one and it showing me the following error:

(TradingView-Webhook-Bot) root@localhost:~/TradingView-Webhook-Bot# 
(TradingView-Webhook-Bot) root@localhost:~/TradingView-Webhook-Bot# 
(TradingView-Webhook-Bot) root@localhost:~/TradingView-Webhook-Bot# 
(TradingView-Webhook-Bot) root@localhost:~/TradingView-Webhook-Bot# 
(TradingView-Webhook-Bot) root@localhost:~/TradingView-Webhook-Bot# 
(TradingView-Webhook-Bot) root@localhost:~/TradingView-Webhook-Bot# python main.py
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    serve(app, host="0.0.0.0", port=80)
  File "/root/TradingView-Webhook-Bot/lib/python3.8/site-packages/waitress/__init__.py", line 13, in serve
    server = _server(app, **kw)
  File "/root/TradingView-Webhook-Bot/lib/python3.8/site-packages/waitress/server.py", line 78, in create_server
    last_serv = TcpWSGIServer(
  File "/root/TradingView-Webhook-Bot/lib/python3.8/site-packages/waitress/server.py", line 244, in __init__
    self.bind_server_socket()
  File "/root/TradingView-Webhook-Bot/lib/python3.8/site-packages/waitress/server.py", line 361, in bind_server_socket
    self.bind(sockaddr)
  File "/root/TradingView-Webhook-Bot/lib/python3.8/site-packages/waitress/wasyncore.py", line 396, in bind
    return self.socket.bind(addr)
OSError: [Errno 98] Address already in use
(TradingView-Webhook-Bot) root@localhost:~/TradingView-Webhook-Bot# 

is anything here messing ?

**Comment by fabston** [comment]
Seems like the port is already taken. Are you running a website or anything?

**Comment by Noofayroz** [comment]
i am not not running anything website on my VPS. I did a fresh install from Ubuntu and it did not help

**Comment by Noofayroz** [comment]
i have the same issue https://github.com/fabston/TradingView-Webhook-Bot/issues/75

**Comment by Noofayroz** [comment]
(TradingView-Webhook-Bot) root@localhost:~/TradingView-Webhook-Bot# python main.py

when i write Python main.py and then hit enter nothing happen. more logs it just freeze
