### ISSUE TITLE
issue when launch

### ISSUE THREAD

**Issue by philobbe** [fabston/TradingView-Webhook-Bot#75]
I have this issue
I configured config.py
with for discord
discord_webhook = 'https://discord.com/api/webhooks/8395932854xxxxxxxxxxxx/MBB7FhOiGxJxxxxxxxxxxxxxxxx'
Do I need to configure something in main.py ?
Thanks

`pi@raspberrypi:~/botdiscord/TradingView-Webhook-Bot $ python main.py
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    serve(app, host="0.0.0.0", port=80)
  File "/home/pi/.local/lib/python3.8/site-packages/waitress/__init__.py", line 13, in serve
    server = _server(app, **kw)
  File "/home/pi/.local/lib/python3.8/site-packages/waitress/server.py", line 78, in create_server
    last_serv = TcpWSGIServer(
  File "/home/pi/.local/lib/python3.8/site-packages/waitress/server.py", line 244, in __init__
    self.bind_server_socket()
  File "/home/pi/.local/lib/python3.8/site-packages/waitress/server.py", line 361, in bind_server_socket
    self.bind(sockaddr)
  File "/home/pi/.local/lib/python3.8/site-packages/waitress/wasyncore.py", line 396, in bind
    return self.socket.bind(addr)
PermissionError: [Errno 13] Permission denied
`

**Comment by philobbe** [comment]
please can you help me I didn't found the problem...

**Comment by fabston** [comment]
Hi there,

I have currently no time in helping open issues. Sorry about that.

**Comment by fabston** [comment]
As arrived, a VPN is required. Regardless of time I’m no supporting RPi setups.

**Comment by philobbe** [comment]
ok thanks anyway for answering

**Comment by philobbe** [comment]
I think I found the problem...I cannot use any port below 1024 without admin rights so I opened 8000 and it seems It works...
