### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by sk1badev** [fabston/TradingView-Webhook-Bot#91]
(TradingView-Webhook-Bot) [root@ovz1 TradingView-Webhook-Bot]# python main.py
Traceback (most recent call last):
  File "main.py", line 46, in <module>
    serve(app, host="0.0.0.0", port=80)
  File "/root/TradingView-Webhook-Bot/TradingView-Webhook-Bot/lib64/python3.6/site-packages/waitress/__init__.py", line 13, in serve
    server = _server(app, **kw)
  File "/root/TradingView-Webhook-Bot/TradingView-Webhook-Bot/lib64/python3.6/site-packages/waitress/server.py", line 85, in create_server
    sockinfo=sockinfo,
  File "/root/TradingView-Webhook-Bot/TradingView-Webhook-Bot/lib64/python3.6/site-packages/waitress/server.py", line 244, in __init__
    self.bind_server_socket()
  File "/root/TradingView-Webhook-Bot/TradingView-Webhook-Bot/lib64/python3.6/site-packages/waitress/server.py", line 361, in bind_server_socket
    self.bind(sockaddr)
  File "/root/TradingView-Webhook-Bot/TradingView-Webhook-Bot/lib64/python3.6/site-packages/waitress/wasyncore.py", line 396, in bind
    return self.socket.bind(addr)
OSError: [Errno 98] Address already in use

**Comment by fabston** [comment]
This isn’t a bug. The address you’re trying to use is already used. As explained in the discussion.
